
-- Create table for common vehicle models
CREATE TABLE public.common_vehicles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  marca VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Insert the 100 popular vehicle models in Brazil
INSERT INTO public.common_vehicles (nome, marca) VALUES
('Audi A3', 'Audi'),
('Audi Q3', 'Audi'),
('BMW 320i', 'BMW'),
('BMW X1', 'BMW'),
('Caoa Chery Arrizo 6', 'Caoa Chery'),
('Caoa Chery Tiggo 5X', 'Caoa Chery'),
('Chevrolet Celta', 'Chevrolet'),
('Chevrolet Montana', 'Chevrolet'),
('Chevrolet Onix', 'Chevrolet'),
('Chevrolet Prisma', 'Chevrolet'),
('Chevrolet S10', 'Chevrolet'),
('Chevrolet Spin', 'Chevrolet'),
('Chevrolet Tracker', 'Chevrolet'),
('Citroën C3', 'Citroën'),
('Fiat Argo', 'Fiat'),
('Fiat Mobi', 'Fiat'),
('Fiat Palio', 'Fiat'),
('Fiat Siena', 'Fiat'),
('Fiat Strada', 'Fiat'),
('Fiat Toro', 'Fiat'),
('Fiat Uno', 'Fiat'),
('Ford EcoSport', 'Ford'),
('Ford Fiesta', 'Ford'),
('Ford Ka', 'Ford'),
('Honda City', 'Honda'),
('Honda Civic', 'Honda'),
('Honda Fit', 'Honda'),
('Honda HR-V', 'Honda'),
('Hyundai Creta', 'Hyundai'),
('Hyundai HB20', 'Hyundai'),
('Jeep Compass', 'Jeep'),
('Jeep Renegade', 'Jeep'),
('Kia Sportage', 'Kia'),
('Land Rover Discovery', 'Land Rover'),
('Land Rover Evoque', 'Land Rover'),
('Mitsubishi ASX', 'Mitsubishi'),
('Mitsubishi L200', 'Mitsubishi'),
('Nissan Kicks', 'Nissan'),
('Nissan March', 'Nissan'),
('Nissan Versa', 'Nissan'),
('Peugeot 2008', 'Peugeot'),
('Peugeot 208', 'Peugeot'),
('Peugeot 3008', 'Peugeot'),
('Peugeot 408', 'Peugeot'),
('Renault Captur', 'Renault'),
('Renault Duster', 'Renault'),
('Renault Kwid', 'Renault'),
('Renault Logan', 'Renault'),
('Renault Sandero', 'Renault'),
('Toyota Corolla', 'Toyota'),
('Toyota Etios', 'Toyota'),
('Toyota Hilux', 'Toyota'),
('Toyota Yaris', 'Toyota'),
('Volkswagen Amarok', 'Volkswagen'),
('Volkswagen Fox', 'Volkswagen'),
('Volkswagen Gol', 'Volkswagen'),
('Volkswagen Jetta', 'Volkswagen'),
('Volkswagen Polo', 'Volkswagen'),
('Volkswagen Saveiro', 'Volkswagen'),
('Volkswagen T-Cross', 'Volkswagen'),
('Volkswagen Tiguan', 'Volkswagen'),
('Volkswagen Up', 'Volkswagen'),
('Volkswagen Voyage', 'Volkswagen'),
('Volvo XC40', 'Volvo'),
('Volvo XC60', 'Volvo'),
('Chevrolet Cruze', 'Chevrolet'),
('Chevrolet Trailblazer', 'Chevrolet'),
('Fiat Fiorino', 'Fiat'),
('Fiat Grand Siena', 'Fiat'),
('Fiat Idea', 'Fiat'),
('Fiat Linea', 'Fiat'),
('Fiat Punto', 'Fiat'),
('Ford Ranger', 'Ford'),
('Honda Accord', 'Honda'),
('Honda CR-V', 'Honda'),
('Hyundai Tucson', 'Hyundai'),
('Jeep Cherokee', 'Jeep'),
('Jeep Grand Cherokee', 'Jeep'),
('Kia Cerato', 'Kia'),
('Kia Soul', 'Kia'),
('Land Rover Defender', 'Land Rover'),
('Land Rover Freelander', 'Land Rover'),
('Mitsubishi Outlander', 'Mitsubishi'),
('Nissan Frontier', 'Nissan'),
('Peugeot Partner', 'Peugeot'),
('Peugeot RCZ', 'Peugeot'),
('Renault Clio', 'Renault'),
('Renault Fluence', 'Renault'),
('Toyota RAV4', 'Toyota'),
('Volkswagen Passat', 'Volkswagen'),
('Volkswagen Touareg', 'Volkswagen'),
('Volvo S60', 'Volvo'),
('Volvo V40', 'Volvo'),
('Chevrolet Cobalt', 'Chevrolet'),
('Chevrolet Meriva', 'Chevrolet'),
('Fiat Doblo', 'Fiat'),
('Fiat Freemont', 'Fiat'),
('Ford Edge', 'Ford'),
('Honda Odyssey', 'Honda'),
('Hyundai Santa Fe', 'Hyundai'),
('Jeep Wrangler', 'Jeep'),
('Kia Sorento', 'Kia'),
('Land Rover Range Rover', 'Land Rover'),
('Mitsubishi Pajero', 'Mitsubishi'),
('Nissan Sentra', 'Nissan'),
('Peugeot 307', 'Peugeot'),
('Renault Kangoo', 'Renault'),
('Toyota SW4', 'Toyota'),
('Volkswagen Golf', 'Volkswagen');

-- Create an index for better search performance
CREATE INDEX idx_common_vehicles_nome ON public.common_vehicles USING gin(to_tsvector('portuguese', nome));

-- Enable RLS (though this table can be publicly readable)
ALTER TABLE public.common_vehicles ENABLE ROW LEVEL SECURITY;

-- Create policy to allow reading common vehicles data
CREATE POLICY "Allow reading common vehicles" 
  ON public.common_vehicles 
  FOR SELECT 
  TO public
  USING (true);
