// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lztntncrgenyvkotfgig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dG50bmNyZ2VueXZrb3RmZ2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDQxMjUsImV4cCI6MjA2NjE4MDEyNX0.WRzsQoyg1oMH6Wq1Xq-5alhVR6P0-HRVqaMEPtto7Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);